# Generated by Django 2.2.5 on 2019-09-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyedetector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRectangle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x0', models.DecimalField(decimal_places=4, max_digits=9)),
                ('x1', models.DecimalField(decimal_places=4, max_digits=9)),
                ('y0', models.DecimalField(decimal_places=4, max_digits=9)),
                ('y1', models.DecimalField(decimal_places=4, max_digits=9)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
