# Generated by Django 2.2.5 on 2019-09-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyedetector', '0003_imagerectangle_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='XYPupilFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=30, max_digits=50)),
                ('y', models.DecimalField(decimal_places=30, max_digits=50)),
            ],
        ),
    ]
