# Generated by Django 2.2.5 on 2019-10-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyedetector', '0009_auto_20190929_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentPointCSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv/')),
            ],
        ),
    ]
