# Generated by Django 2.2.5 on 2019-10-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyedetector', '0010_experimentpointcsv'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.TextField(help_text='Funcion en formato de codigo python', max_length=200)),
            ],
        ),
    ]
